version: '3'
services:
  ginblog:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    volumes:
      - ./backend:/go/src/app
    command: >
      reflex
      -r (\.go$$|go\.mod)
      -s go run main.go
